[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"

# Configurações para Netlify Functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Variáveis de ambiente para as Functions
[functions.environment]
  OPENPIX_API_KEY = "Q2xpZW50X0lkX2VhNGNhZGYzLTM0N2YtNDEwYi04MDY0LTQ1MmY3ZTgwYjA4MjpDbGllbnRfU2VjcmV0X2ZLMkk1WFpWam9sd1FKcTMwYXJNdUZ5Qk5ZcG5Md0RwSjljcWdidTJhTWs9"
  OPENPIX_CORP_ID = "d14a8e82-1ab7-4dee-a1a5-6d86c3781ccb"
  API_BASE_URL = "https://api.woovi.com"
  WEBHOOK_URL = "https://interbox-captacao.netlify.app/webhook"
  ADMIN_API_KEY = "interbox2025"
  # Configurações para o sistema de seguros
  SEGURO_VALOR_FIXO = "39.90"
  SEGURO_PARCEIRO_CNPJ = "00.283.283/0001-26"
  SEGURO_EMAIL_COMPROVANTE = "financeirocorretora@gruposaga.com.br"
  
  # Supabase - NOVAS CHAVES
  SUPABASE_URL = "https://ymriypyyirnwctyitcsu.supabase.co"
  SUPABASE_ANON_KEY = "your_supabase_anon_key_here"
  SUPABASE_SERVICE_ROLE_KEY = "your_supabase_service_role_key_here"

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
